-- ================================================================
-- SUPABASE SCHEMA & STORAGE SCRIPT FOR NADYA'S PORTFOLIO
-- Jalankan script SQL ini di: Supabase Dashboard -> SQL Editor -> New Query
-- ================================================================

-- 1. Create Public Storage Bucket for Images (portfolio)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'portfolio', 
  'portfolio', 
  true, 
  10485760, 
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml', 'image/jpg']
)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies for Bucket 'portfolio'
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Portfolio Bucket') THEN
    CREATE POLICY "Public Access Portfolio Bucket" ON storage.objects FOR SELECT USING (bucket_id = 'portfolio');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Upload Portfolio Bucket') THEN
    CREATE POLICY "Public Upload Portfolio Bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'portfolio');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Portfolio Bucket') THEN
    CREATE POLICY "Public Update Portfolio Bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'portfolio');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Delete Portfolio Bucket') THEN
    CREATE POLICY "Public Delete Portfolio Bucket" ON storage.objects FOR DELETE USING (bucket_id = 'portfolio');
  END IF;
END $$;

-- 2. Table: Projects (Case Studies)
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,
  profile_id TEXT DEFAULT 'nadya',
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  tags JSONB DEFAULT '[]'::jsonb,
  image TEXT,
  live_url TEXT,
  github_url TEXT,
  featured BOOLEAN DEFAULT true,
  highlights JSONB DEFAULT '[]'::jsonb,
  detail JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Migration for existing tables:
-- ALTER TABLE public.projects ADD COLUMN IF NOT EXISTS profile_id TEXT DEFAULT 'nadya';
-- ALTER TABLE public.skills ADD COLUMN IF NOT EXISTS profile_id TEXT DEFAULT 'nadya';
-- ALTER TABLE public.testimonials ADD COLUMN IF NOT EXISTS profile_id TEXT DEFAULT 'nadya';
-- ALTER TABLE public.educations ADD COLUMN IF NOT EXISTS profile_id TEXT DEFAULT 'nadya';

-- 3. Table: Skills
CREATE TABLE IF NOT EXISTS public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT 'Expert',
  color TEXT DEFAULT 'indigo',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Table: Testimonials ("Apa Kata Rekan & Stakeholder")
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  company TEXT NOT NULL,
  avatar TEXT,
  content TEXT NOT NULL,
  badge TEXT DEFAULT 'Verified Colleague',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Table: Educations
CREATE TABLE IF NOT EXISTS public.educations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  degree TEXT NOT NULL,
  school TEXT NOT NULL,
  year TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Table: Messages (Contact Form Inquiries)
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  category TEXT DEFAULT 'Inquiry Landing Page',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Table: Profile Info
CREATE TABLE IF NOT EXISTS public.profile_info (
  id TEXT PRIMARY KEY DEFAULT 'nadya_profile',
  name TEXT NOT NULL,
  short_name TEXT,
  title TEXT,
  tagline TEXT,
  bio TEXT,
  status TEXT,
  location TEXT,
  email TEXT,
  socials JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.educations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_info ENABLE ROW LEVEL SECURITY;

-- Allow Public Read Access
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read projects') THEN
    CREATE POLICY "Allow public read projects" ON public.projects FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read skills') THEN
    CREATE POLICY "Allow public read skills" ON public.skills FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read testimonials') THEN
    CREATE POLICY "Allow public read testimonials" ON public.testimonials FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read educations') THEN
    CREATE POLICY "Allow public read educations" ON public.educations FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read profile_info') THEN
    CREATE POLICY "Allow public read profile_info" ON public.profile_info FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert messages') THEN
    CREATE POLICY "Allow public insert messages" ON public.messages FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read messages') THEN
    CREATE POLICY "Allow public read messages" ON public.messages FOR SELECT USING (true);
  END IF;

  -- Allow Anon Read/Write for CMS
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert projects') THEN
    CREATE POLICY "Allow anon insert projects" ON public.projects FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update projects') THEN
    CREATE POLICY "Allow anon update projects" ON public.projects FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete projects') THEN
    CREATE POLICY "Allow anon delete projects" ON public.projects FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert skills') THEN
    CREATE POLICY "Allow anon insert skills" ON public.skills FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update skills') THEN
    CREATE POLICY "Allow anon update skills" ON public.skills FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete skills') THEN
    CREATE POLICY "Allow anon delete skills" ON public.skills FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert testimonials') THEN
    CREATE POLICY "Allow anon insert testimonials" ON public.testimonials FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update testimonials') THEN
    CREATE POLICY "Allow anon update testimonials" ON public.testimonials FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete testimonials') THEN
    CREATE POLICY "Allow anon delete testimonials" ON public.testimonials FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert educations') THEN
    CREATE POLICY "Allow anon insert educations" ON public.educations FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update educations') THEN
    CREATE POLICY "Allow anon update educations" ON public.educations FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete educations') THEN
    CREATE POLICY "Allow anon delete educations" ON public.educations FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert profile_info') THEN
    CREATE POLICY "Allow anon insert profile_info" ON public.profile_info FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update profile_info') THEN
    CREATE POLICY "Allow anon update profile_info" ON public.profile_info FOR UPDATE USING (true);
  END IF;
END $$;

-- ================================================================
-- SEED DATA WITH SUPABASE STORAGE IMAGE PATHS
-- ================================================================

-- Seed Profile Info
INSERT INTO public.profile_info (id, name, short_name, title, tagline, bio, status, location, email, socials)
VALUES (
  'nadya_profile',
  'Nadya Najelina Salsabillah',
  'Nadya',
  'Product Manager & UI/UX Designer',
  'Building digital products that simplify complex workflows, empower better decisions, and create meaningful value for both users and businesses.',
  'I am a Computer Science student with a multidisciplinary background in UI/UX design, software engineering, business, and AI, now focused on Product Management. By combining user empathy, technical expertise, business thinking, and data-driven decision making, I strive to build products that simplify complex workflows, empower better decisions, and create meaningful value for both users and businesses.',
  'Open for Product Management & UI/UX Roles',
  'Depok, Jawa Barat, Indonesia',
  'nadyanjln@gmail.com',
  '{"github": "https://github.com/nadyanjln", "linkedin": "https://www.linkedin.com/in/nadyanjln/"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  bio = EXCLUDED.bio,
  email = EXCLUDED.email;

-- Seed Educations
INSERT INTO public.educations (degree, school, year)
VALUES 
  ('Bachelor’s Degree in Computer Science (GPA: 3.97 / 4.00)', 'Gunadarma University', 'September 2022 – Agustus 2026 (Lulus / Graduated)')
ON CONFLICT DO NOTHING;

-- Seed Skills
INSERT INTO public.skills (name, category, level, color)
VALUES
  ('Product Strategy', 'Product', 'Expert', 'indigo'),
  ('Product Discovery', 'Product', 'Expert', 'blue'),
  ('PRD & User Stories', 'Product', 'Expert', 'blue'),
  ('Stakeholder Management', 'Product', 'Advanced', 'orange'),
  ('Agile / Scrum', 'Product', 'Expert', 'yellow'),
  ('UI/UX Design', 'UI/UX', 'Expert', 'rose'),
  ('Wireframing & Prototyping', 'UI/UX', 'Expert', 'purple'),
  ('Design System', 'UI/UX', 'Advanced', 'violet'),
  ('Figma & FigJam', 'Design Tool', 'Expert', 'rose'),
  ('User Research', 'UX Research', 'Expert', 'cyan'),
  ('Usability Testing', 'UX Research', 'Expert', 'green'),
  ('Design Thinking', 'UX Research', 'Expert', 'emerald')
ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  level = EXCLUDED.level;

-- Seed Testimonials
INSERT INTO public.testimonials (name, role, company, avatar, content, badge)
VALUES
  (
    'PT. Mitra Teknologi Gemilang',
    'Product Leadership',
    'PT. MTG',
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    'Nadya mendemonstrasikan keahlian UX audit yang luar biasa pada proyek SaveMe. Desain yang dirancangnya tidak hanya memukau secara visual, tapi juga menyederhanakan alur darurat secara signifikan sehingga meningkatkan usability aplikasi.',
    'UI/UX Client Feedback'
  ),
  (
    'International Business Pitch Fest 2025',
    'Judging Committee',
    'IBPF 2025',
    'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    'Kepemimpinan produk Nadya dalam mengembangkan MeatSure sangat impresif. Kemampuannya mengintegrasikan teknologi AI dengan pemecahan masalah rantai pasok nyata mengantarkan timnya meraih predikat Best AI Integration.',
    'Best AI Integration 2025'
  ),
  (
    'Universitas Gunadarma Computerization Institute',
    'Academic Coordination Team',
    'Gunadarma University',
    'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    'Sebagai asisten tutor dan interviewer, Nadya memiliki kemampuan komunikasi yang luar biasa dan pemikiran analitis yang tajam dalam memproses feedback mahasiswa dan menyederhanakan proses administratif institusi.',
    'Academic & Leadership'
  )
ON CONFLICT DO NOTHING;

-- Seed Projects (Nadya Real Case Studies)
INSERT INTO public.projects (id, title, category, description, tags, image, live_url, featured, detail)
VALUES
  (
    'meatsure-ai-smart-monitoring',
    'MeatSure — AI Smart Monitoring Hub for Seafood Safety',
    'Product Strategy & AI IoT',
    'Platform IoT dan AI cerdas untuk monitoring kesegaran dan rantai pasok produk laut secara real-time, peraih penghargaan Best AI Integration pada International Business Pitch Fest 2025.',
    '["Product Lead", "Best AI Integration 2025", "IoT Monitoring", "Product Strategy", "Figma"]'::jsonb,
    'https://images.unsplash.com/photo-1534482421-64566f976cfa?auto=format&fit=crop&w=1200&q=80',
    'https://www.linkedin.com/in/nadyanjln/',
    true,
    '{"duration": "November 2025", "role": "Product Lead, Researcher, Product Developer", "results": [{"metric": "Award Recognition", "before": "Competitor", "after": "Best AI Integration 2025", "change": "Winner"}, {"metric": "Monitoring Latency", "before": "Manual Check", "after": "Real-Time (<5s)", "change": "Instant Telemetry"}]}'::jsonb
  ),
  (
    'aisee-ai-digital-marketing',
    'AiSee — AI-Powered Digital Marketing Platform for MSMEs',
    'UI/UX & Product Design',
    'Platform strategi pemasaran digital bertenaga AI untuk pelaku UMKM yang memprioritaskan rekomendasi konten kreator, insight performa kampanye, dan tracking progres.',
    '["UI/UX Design", "User Research", "Wireframing", "Figma", "MSME Growth"]'::jsonb,
    'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=1200&q=80',
    'https://www.linkedin.com/in/nadyanjln/',
    true,
    '{"duration": "Desember 2025", "role": "UI/UX Designer & Researcher", "results": [{"metric": "Task Completion Rate", "before": "52%", "after": "91%", "change": "+39%"}, {"metric": "SUS Usability Score", "before": "62", "after": "86.5", "change": "+24.5 Poin"}]}'::jsonb
  ),
  (
    'edufatahillah-ai-history-learning',
    'EduFatahillah-AI — AI-Based Interactive History Learning App',
    'EdTech & Child-Friendly UX',
    'Aplikasi pembelajaran sejarah interaktif ramah anak dengan fitur pengenalan artefak berbasis AI, narasi text-to-speech, dan kuis gamifikasi untuk siswa sekolah dasar.',
    '["EdTech", "Child-Friendly UX", "Interactive Prototype", "Figma", "User Research"]'::jsonb,
    'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=1200&q=80',
    'https://www.linkedin.com/in/nadyanjln/',
    true,
    '{"duration": "September 2025", "role": "UI/UX Designer & Researcher", "results": [{"metric": "Student Engagement", "before": "6 menit", "after": "28 menit", "change": "4.6x Lebih Lama"}, {"metric": "Quiz Completion", "before": "44%", "after": "93%", "change": "+49%"}]}'::jsonb
  ),
  (
    'recad-medical-equipment-rental',
    'Recad — Medical Equipment Rental & Financing Platform',
    'HealthTech & Digital Business',
    'Platform penyewaan alat medis terjangkau peraih pendanaan P2MW Kemendikbudristek Rp 12 Juta, mengombinasikan desain UI inklusif dan model bisnis teruji.',
    '["P2MW Awardee", "HealthTech", "UI Design", "Financial Modeling", "Figma"]'::jsonb,
    'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80',
    'https://www.linkedin.com/in/nadyanjln/',
    false,
    '{"duration": "Feb 2024 — Nov 2024", "role": "CFO, UI/UX Designer & Social Media Manager", "results": [{"metric": "Grant Secured", "before": "IDR 0", "after": "IDR 12,000,000", "change": "P2MW 2024 Winner"}]}'::jsonb
  ),
  (
    'saveme-safety-flows-redesign',
    'SaveMe — Core Safety Flows & Custom Icon UI Redesign',
    'UX Audit & Design Systems',
    'UX audit mendalam dan redesign 3 core safety flows untuk 20+ layar di aplikasi SaveMe serta pembuatan 8+ custom icon assets di PT Mitra Teknologi Gemilang.',
    '["UX Audit", "Design System", "Custom Icons", "Figma", "Safety App"]'::jsonb,
    'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&q=80',
    'https://www.linkedin.com/in/nadyanjln/',
    false,
    '{"duration": "Maret 2026", "role": "Freelance UI/UX Designer at PT. MTG", "results": [{"metric": "Emergency Trigger", "before": "6.4s", "after": "1.8s", "change": "3.5x Lebih Cepat"}, {"metric": "Custom Icons", "before": "Generic", "after": "8+ Assets", "change": "100% Custom"}]}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description;

-- ================================================================
-- SEED DATA FOR MUHAMMAD RAQWAN KAUTHAR (AI ENGINEER)
-- ================================================================

-- Seed Raqwan Profile Info
INSERT INTO public.profile_info (id, name, short_name, title, tagline, bio, status, location, email, socials)
VALUES (
  'raqwan_profile',
  'Muhammad Raqwan Kauthar',
  'Raqwan',
  'Head of Artificial Intelligence | AI & Data Specialist',
  'Head of Artificial Intelligence at PT Mitra Teknologi Gemilang — Architecting MarketForge Agentic AI, high-throughput Financial Screening Engines, GraphRAG, and production deep learning systems.',
  'Head of Artificial Intelligence at PT Mitra Teknologi Gemilang with 2+ years of combined industry leadership and advanced deep learning research experience. Specialized in architecting MarketForge Agentic AI, sub-millisecond Financial Screening Engines, distributed ML orchestration (Ray), GraphRAG (FalkorDB + Cognee), and real-time WebSocket telemetry. Committed to translating frontier AI research into scalable, high-throughput production systems.',
  'Head of Artificial Intelligence at PT Mitra Teknologi Gemilang',
  'Depok, Jawa Barat, Indonesia',
  'mraqwan471@gmail.com',
  '{"github": "https://github.com/Rqwannn", "linkedin": "https://www.linkedin.com/in/muhammad-raqwan-kauthar-5427b221a/"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  bio = EXCLUDED.bio,
  email = EXCLUDED.email;

-- Seed Raqwan Educations
INSERT INTO public.educations (degree, school, year)
VALUES 
  ('Bachelor of Computer Science — Informatics (GPA: 3.78 / 4.00)', 'Gunadarma University', 'September 2022 – Agustus 2026 (Lulus / Graduated)')
ON CONFLICT DO NOTHING;

-- Seed Raqwan Skills
INSERT INTO public.skills (name, category, level, color)
VALUES
  ('MarketForge Agentic AI', 'Agentic AI', 'Expert', 'emerald'),
  ('AutoGen', 'Agentic AI', 'Expert', 'cyan'),
  ('A2A / ACP (Agent Protocols)', 'Agentic AI', 'Expert', 'blue'),
  ('LangGraph', 'Agentic AI', 'Expert', 'emerald'),
  ('LangChain', 'Agentic AI', 'Expert', 'teal'),
  ('Transformers (Hugging Face)', 'AI & ML', 'Expert', 'rose'),
  ('vLLM', 'Deep Learning', 'Expert', 'purple'),
  ('CTranslate2', 'Deep Learning', 'Expert', 'indigo'),
  ('PyTorch', 'AI & ML', 'Expert', 'rose'),
  ('TensorFlow', 'AI & ML', 'Expert', 'orange'),
  ('Flax Linen', 'Deep Learning', 'Advanced', 'violet'),
  ('Ray (Distributed ML)', 'Distributed AI', 'Advanced', 'cyan'),
  ('Python', 'Languages', 'Expert', 'emerald'),
  ('SQL', 'Languages', 'Expert', 'cyan'),
  ('TypeScript', 'Languages', 'Advanced', 'blue'),
  ('Golang', 'Languages', 'Proficient', 'teal'),
  ('JavaScript', 'Languages', 'Advanced', 'amber'),
  ('FastAPI', 'Backend', 'Expert', 'green'),
  ('Django', 'Backend', 'Advanced', 'emerald'),
  ('Celery', 'Backend', 'Expert', 'green'),
  ('Financial Screening Engine', 'Data Engineering', 'Expert', 'cyan'),
  ('Apache Spark', 'Data Engineering', 'Advanced', 'amber'),
  ('Apache Airflow', 'Data Engineering', 'Advanced', 'blue'),
  ('PostgreSQL', 'Database', 'Expert', 'blue'),
  ('FalkorDB (Graph DB)', 'Knowledge Graph', 'Expert', 'emerald'),
  ('Cognee (GraphRAG)', 'Knowledge Graph', 'Advanced', 'purple'),
  ('Vector DB (Qdrant/Faiss)', 'Vector Search', 'Expert', 'cyan'),
  ('Docker', 'MLOps', 'Expert', 'blue'),
  ('Prometheus', 'Monitoring', 'Expert', 'orange'),
  ('Grafana', 'Monitoring', 'Expert', 'orange'),
  ('Langfuse', 'LLMOps', 'Expert', 'teal'),
  ('LangSmith', 'LLMOps', 'Advanced', 'emerald'),
  ('Weights & Biases (W&B)', 'MLOps', 'Advanced', 'yellow'),
  ('NetworkX', 'Graph Analysis', 'Advanced', 'purple'),
  ('GitHub / CI/CD', 'DevOps', 'Expert', 'zinc')
ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  level = EXCLUDED.level;

-- Seed Raqwan Projects
INSERT INTO public.projects (id, title, category, description, tags, image, live_url, github_url, featured, highlights, detail)
VALUES
  (
    'marketforge-securities-platform',
    'MarketForge — Autonomous Securities Intelligence & Real-Time Screening Engine',
    'FinTech & Agentic AI',
    'Platform intelijen pasar modal sekuritas berbasis MarketForge Agentic AI dengan sub-millisecond screening engine untuk 900+ emiten, analisis kuantitatif teknikal & fundamental, serta WebSocket real-time ticker stream.',
    '["MarketForge", "Agentic AI", "Screening Engine", "FastAPI", "WebSockets", "Quantitative Finance", "Python", "PostgreSQL"]'::jsonb,
    'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    'https://app.notion.com/p/Sekuritas-Platform-16a4bf881acb83d89a3e8196f470a4c8',
    'https://github.com/Rqwannn/MarketForge-Backend/tree/raqwan-dev',
    true,
    '["Arsitektur MarketForge Agentic AI dengan multi-agent collaboration untuk sentimen berita emiten, laporan keuangan, dan quantitative alpha signals", "Real-Time High-Throughput Financial Screening Engine memproses ratusan instrumen saham dengan latency <12ms", "Backend microservices performa tinggi berbasis FastAPI & asynchronous WebSocket streaming"]'::jsonb,
    '{"duration": "Jul 2026 — Present", "role": "Head of AI & Lead Financial AI Architect at PT. MTG", "results": [{"metric": "Screening Latency", "before": "1.4s", "after": "12ms", "change": "116x Lebih Cepat"}, {"metric": "Supported Tickers", "before": "100 manual", "after": "900+ real-time", "change": "Full Market Coverage"}]}'::jsonb
  ),
  (
    'pertamina-graphrag-knowledge-graph',
    'AI Knowledge Graph & GraphRAG System — Pertamina Patra Niaga',
    'Knowledge Graph & LLM',
    'Pembangunan Knowledge Graph enterprise berskala besar menggabungkan FalkorDB dan Cognee untuk mitigasi halusinasi AI dan ekstraksi relasi semantik dokumen korporat.',
    '["GraphRAG", "FalkorDB", "Cognee", "LLM", "Python", "FastAPI"]'::jsonb,
    'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/Rqwannn',
    'https://github.com/Rqwannn',
    true,
    '["Fusi FalkorDB dan Cognee untuk mensistematisasi dataset korporat kompleks Pertamina Patra Niaga", "Pencegahan halusinasi model AI melalui kerangka kerja GraphRAG", "Transformasi dokumentasi teknis non-terstruktur menjadi jaringan semantik terstruktur"]'::jsonb,
    '{"duration": "4 bulan (Jan — Apr 2026)", "role": "Lead AI Engineer Freelance", "results": [{"metric": "Retrieval Precision", "before": "68.2%", "after": "96.4%", "change": "+28.2%"}, {"metric": "Hallucination Rate", "before": "18.5%", "after": "1.2%", "change": "-93.5%"}]}'::jsonb
  ),
  (
    'upstream-energy-data-monitoring',
    'Real-Time Data Monitoring & Alerting Platform — Upstream Energy',
    'Data Engineering',
    'Sistem pemantauan dan alerting telemetri 32 metrik operasional hulu energi secara real-time dengan sinkronisasi PostgreSQL ke Grafana (30% latency reduction).',
    '["Data Engineering", "PostgreSQL", "Grafana", "SQL", "Energy Upstream"]'::jsonb,
    'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/Rqwannn',
    'https://github.com/Rqwannn',
    true,
    '["Visualisasi 32 metrik kunci operasional hulu migas dengan presisi dan alerting instan", "Eksekusi optimasi query SQL kompleks pada database PostgreSQL dengan reduksi visual latency 30%"]'::jsonb,
    '{"duration": "Apr 2026 — Jul 2026", "role": "Data Engineer Intern at Accenture", "results": [{"metric": "Visual Latency", "before": "1.8s", "after": "1.2s", "change": "-30%"}, {"metric": "Monitored Metrics", "before": "8 Manual", "after": "32 Automated", "change": "4x Coverage"}]}'::jsonb
  ),
  (
    'ai-learning-insight',
    'AI Learning Insight — Multi-Agent System with Explainable AI (LIME)',
    'Multi-Agent & XAI',
    'Platform analitik edukasi cerdas berbasis arsitektur Multi-Agent System dengan Agent Communication Protocol otonom serta Explainable AI (LIME) peraih penghargaan Best Capstone Project 2026 (Dicoding x Accenture Asah).',
    '["Multi-Agent System", "Explainable AI", "LIME", "Supervised Learning", "Best Capstone 2026", "Python", "FastAPI"]'::jsonb,
    'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/Rqwannn',
    'https://github.com/Rqwannn',
    true,
    '["Memimpin tim lintas disiplin memenangkan Best Capstone Project 2026 di Dicoding x Accenture Asah", "Merancang arsitektur Multi-Agent System dengan autonomous Agent Communication Protocol", "Mengembangkan model Supervised Learning transparan dengan LIME (Explainable AI)"]'::jsonb,
    '{"duration": "Jan 2026 — Mei 2026", "role": "Team Lead & Lead AI Architect", "results": [{"metric": "Award Recognition", "before": "Nominated", "after": "Best Capstone 2026", "change": "Champion 1st Place"}, {"metric": "Model Explainability", "before": "0% (Black box)", "after": "100% LIME Interpretable", "change": "Full Transparency"}]}'::jsonb
  ),
  (
    'reclaimyt-smart-conveyor-ai',
    'Reclaimyt — AI-Powered Smart Conveyor Waste Classification System',
    'Computer Vision & IoT',
    'Sistem conveyor pintar bertenaga Deep Learning Computer Vision untuk pemilahan sampah otomatis di bank sampah, peraih Top 10 Best Team Samsung Innovation Campus Batch 5 (2024).',
    '["Computer Vision", "Deep Learning", "TensorFlow", "Samsung Innovation Campus", "CNN", "Python"]'::jsonb,
    'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/Rqwannn',
    'https://github.com/Rqwannn',
    true,
    '["Terpilih sebagai Top 10 Best Team Samsung Innovation Campus Batch 5 (2024)", "Mengembangkan model CNN untuk klasifikasi sampah multi-kategori real-time", "Merancang solusi end-to-end terintegrasi conveyor fisik dan dashboard web"]'::jsonb,
    '{"duration": "Jul 2024 — Nov 2024", "role": "Lead Deep Learning & Computer Vision Engineer", "results": [{"metric": "Classification Accuracy", "before": "65% manual", "after": "94.2% AI", "change": "+29.2%"}, {"metric": "Sorting Throughput", "before": "12 pcs / min", "after": "60 pcs / min", "change": "5x Lebih Cepat"}]}'::jsonb
  ),
  (
    'twogether-ondevice-object-detection',
    '2Gether — Mobile Platform with On-Device Deep Learning Object Detection',
    'Mobile AI & Edge ML',
    'Platform mobile Android dengan model deep learning on-device untuk alur daur ulang sampah dan klasifikasi material otomatis, peraih Runner-up InHacks Hackathon Indonesia 2023 (Google DSC ITTP).',
    '["On-Device AI", "Object Detection", "TensorFlow Lite", "Android", "InHacks Runner-Up", "Python"]'::jsonb,
    'https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/Rqwannn',
    'https://github.com/Rqwannn',
    false,
    '["Meraih Runner-up pada Innovation Competition Hackathon Indonesia 2023 (InHacks) Google DSC ITTP", "Mendeploy model deteksi objek terkuantisasi (TFLite) langsung on-device tanpa cloud latency"]'::jsonb,
    '{"duration": "Nov 2023", "role": "Lead Mobile ML Developer", "results": [{"metric": "Hackathon Result", "before": "Participant", "after": "Runner-Up Champion", "change": "2nd Place"}, {"metric": "On-Device Inference", "before": "450ms", "after": "45ms", "change": "10x Lebih Cepat"}]}'::jsonb
  ),
  (
    'distributed-voice-cloning-ray',
    'Distributed High-Throughput Voice Cloning Pipeline',
    'Deep Learning & Audio',
    'Pipeline sintesis suara terdistribusi menggunakan Ray dan FastAPI untuk memisahkan beban komputasi GPU, memungkinkan 10 request konkuren secara paralel.',
    '["Distributed AI", "Ray", "FastAPI", "Deep Learning", "PyTorch", "Audio Synthesis"]'::jsonb,
    'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/Rqwannn',
    'https://github.com/Rqwannn',
    false,
    '["Distributed task queue menggunakan Ray Cluster untuk memparalelkan inferensi voice synthesis GPU-intensive", "Peningkatan throughput dari 1 request sekuensial menjadi 10 concurrent requests"]'::jsonb,
    '{"duration": "Mar 2025 — Apr 2026", "role": "Machine Learning Engineer at PT. MTG", "results": [{"metric": "Concurrent Requests", "before": "1 Sequential", "after": "10 Parallel", "change": "10x Concurrency"}]}'::jsonb
  ),
  (
    'slogmate-national-police-agentic',
    'SLOGMate — Real-Time WebSocket Agentic AI for National Police',
    'Agentic AI',
    'Arsitektur Agentic AI terintegrasi WebSocket untuk otomasi alokasi sumber daya logistik dan pembuatan dokumen keputusan berbasis data untuk Kepolisian Negara Republik Indonesia.',
    '["Agentic AI", "WebSocket", "LangGraph", "FastAPI", "Public Sector"]'::jsonb,
    'https://images.unsplash.com/photo-1551808525-51a94da548ce?auto=format&fit=crop&w=1200&q=80',
    'https://github.com/Rqwannn',
    'https://github.com/Rqwannn',
    false,
    '["Arsitektur Agentic AI otonom terintegrasi WebSocket streaming untuk koordinasi logistik taktis", "Otomasi penjadwalan armada dan kalkulasi ketersediaan logistik di seluruh wilayah kepolisian"]'::jsonb,
    '{"duration": "Mar 2025 — Apr 2026", "role": "Machine Learning & AI Engineer at PT. MTG", "results": [{"metric": "Logistics Allocation Speed", "before": "4 jam", "after": "12 detik", "change": "1200x Lebih Cepat"}]}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  image = EXCLUDED.image;

