-- ================================================================
-- SUPABASE SCHEMA & STORAGE SCRIPT FOR NADYA'S PORTFOLIO
-- Jalankan script SQL ini di: Supabase Dashboard -> SQL Editor -> New Query
-- ================================================================

-- 1. Create Public Storage Bucket for Images (portfolio)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'portfolio', 
  'portfolio', 
  true, 
  10485760, 
  ARRAY['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml', 'image/jpg']
)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage Policies for Bucket 'portfolio'
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Access Portfolio Bucket') THEN
    CREATE POLICY "Public Access Portfolio Bucket" ON storage.objects FOR SELECT USING (bucket_id = 'portfolio');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Upload Portfolio Bucket') THEN
    CREATE POLICY "Public Upload Portfolio Bucket" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'portfolio');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Update Portfolio Bucket') THEN
    CREATE POLICY "Public Update Portfolio Bucket" ON storage.objects FOR UPDATE USING (bucket_id = 'portfolio');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Delete Portfolio Bucket') THEN
    CREATE POLICY "Public Delete Portfolio Bucket" ON storage.objects FOR DELETE USING (bucket_id = 'portfolio');
  END IF;
END $$;

-- 2. Table: Projects (Case Studies)
CREATE TABLE IF NOT EXISTS public.projects (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT,
  tags JSONB DEFAULT '[]'::jsonb,
  image TEXT,
  live_url TEXT,
  github_url TEXT,
  featured BOOLEAN DEFAULT true,
  highlights JSONB DEFAULT '[]'::jsonb,
  detail JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Table: Skills
CREATE TABLE IF NOT EXISTS public.skills (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  level TEXT NOT NULL DEFAULT 'Expert',
  color TEXT DEFAULT 'indigo',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 4. Table: Testimonials ("Apa Kata Rekan & Stakeholder")
CREATE TABLE IF NOT EXISTS public.testimonials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  company TEXT NOT NULL,
  avatar TEXT,
  content TEXT NOT NULL,
  badge TEXT DEFAULT 'Verified Colleague',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. Table: Educations
CREATE TABLE IF NOT EXISTS public.educations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  degree TEXT NOT NULL,
  school TEXT NOT NULL,
  year TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 6. Table: Messages (Contact Form Inquiries)
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  message TEXT NOT NULL,
  category TEXT DEFAULT 'Inquiry Landing Page',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 7. Table: Profile Info
CREATE TABLE IF NOT EXISTS public.profile_info (
  id TEXT PRIMARY KEY DEFAULT 'nadya_profile',
  name TEXT NOT NULL,
  short_name TEXT,
  title TEXT,
  tagline TEXT,
  bio TEXT,
  status TEXT,
  location TEXT,
  email TEXT,
  socials JSONB DEFAULT '{}'::jsonb,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.skills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.educations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profile_info ENABLE ROW LEVEL SECURITY;

-- Allow Public Read Access
DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read projects') THEN
    CREATE POLICY "Allow public read projects" ON public.projects FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read skills') THEN
    CREATE POLICY "Allow public read skills" ON public.skills FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read testimonials') THEN
    CREATE POLICY "Allow public read testimonials" ON public.testimonials FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read educations') THEN
    CREATE POLICY "Allow public read educations" ON public.educations FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read profile_info') THEN
    CREATE POLICY "Allow public read profile_info" ON public.profile_info FOR SELECT USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert messages') THEN
    CREATE POLICY "Allow public insert messages" ON public.messages FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read messages') THEN
    CREATE POLICY "Allow public read messages" ON public.messages FOR SELECT USING (true);
  END IF;

  -- Allow Anon Read/Write for CMS
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert projects') THEN
    CREATE POLICY "Allow anon insert projects" ON public.projects FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update projects') THEN
    CREATE POLICY "Allow anon update projects" ON public.projects FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete projects') THEN
    CREATE POLICY "Allow anon delete projects" ON public.projects FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert skills') THEN
    CREATE POLICY "Allow anon insert skills" ON public.skills FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update skills') THEN
    CREATE POLICY "Allow anon update skills" ON public.skills FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete skills') THEN
    CREATE POLICY "Allow anon delete skills" ON public.skills FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert testimonials') THEN
    CREATE POLICY "Allow anon insert testimonials" ON public.testimonials FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update testimonials') THEN
    CREATE POLICY "Allow anon update testimonials" ON public.testimonials FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete testimonials') THEN
    CREATE POLICY "Allow anon delete testimonials" ON public.testimonials FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert educations') THEN
    CREATE POLICY "Allow anon insert educations" ON public.educations FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update educations') THEN
    CREATE POLICY "Allow anon update educations" ON public.educations FOR UPDATE USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon delete educations') THEN
    CREATE POLICY "Allow anon delete educations" ON public.educations FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon insert profile_info') THEN
    CREATE POLICY "Allow anon insert profile_info" ON public.profile_info FOR INSERT WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow anon update profile_info') THEN
    CREATE POLICY "Allow anon update profile_info" ON public.profile_info FOR UPDATE USING (true);
  END IF;
END $$;

-- ================================================================
-- SEED DATA WITH SUPABASE STORAGE IMAGE PATHS
-- ================================================================

-- Seed Profile Info
INSERT INTO public.profile_info (id, name, short_name, title, tagline, bio, status, location, email, socials)
VALUES (
  'nadya_profile',
  'Nadya Najelina Salsabillah',
  'Nadya',
  'Product Manager & UI/UX Designer',
  'Merancang produk digital yang berdampak — dari riset pengguna hingga desain interface yang intuitif dan scalable.',
  'Hi! Saya Nadya Najelina Salsabillah, seorang Product Manager & UI/UX Designer yang passionate dalam menciptakan pengalaman digital yang bermakna. Saya menggabungkan pemikiran strategis product management dengan keahlian visual design untuk memastikan setiap produk tidak hanya indah secara estetika, tetapi juga memberikan nilai nyata bagi pengguna dan bisnis.',
  'Open for Product & Design roles',
  'Indonesia',
  'nadyanjln@gmail.com',
  '{"github": "https://github.com/nadyanjln", "linkedin": "https://www.linkedin.com/in/nadyanjln/"}'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  title = EXCLUDED.title,
  bio = EXCLUDED.bio,
  email = EXCLUDED.email;

-- Seed Educations
INSERT INTO public.educations (degree, school, year)
VALUES 
  ('S1 Informatika (Sarjana Komputer)', 'Universitas Gunadarma', '2020 - 2024')
ON CONFLICT DO NOTHING;

-- Seed Skills
INSERT INTO public.skills (name, category, level, color)
VALUES
  ('Product Strategy', 'Product', 'Expert', 'indigo'),
  ('User Research', 'UX Research', 'Expert', 'cyan'),
  ('Wireframing & Prototyping', 'UI/UX', 'Expert', 'purple'),
  ('Figma', 'Design Tool', 'Expert', 'pink'),
  ('Design System', 'UI/UX', 'Advanced', 'violet'),
  ('PRD & User Stories', 'Product', 'Expert', 'blue'),
  ('A/B Testing', 'Product', 'Advanced', 'emerald'),
  ('Data-Driven Decision', 'Product', 'Advanced', 'amber'),
  ('Usability Testing', 'UX Research', 'Expert', 'green'),
  ('Stakeholder Management', 'Product', 'Advanced', 'orange'),
  ('Agile / Scrum', 'Product', 'Expert', 'yellow'),
  ('Interaction Design', 'UI/UX', 'Expert', 'rose')
ON CONFLICT (name) DO UPDATE SET
  category = EXCLUDED.category,
  level = EXCLUDED.level;

-- Seed Testimonials (With Supabase Storage Avatars)
INSERT INTO public.testimonials (name, role, company, avatar, content, badge)
VALUES
  (
    'Rian Pratama',
    'VP of Product',
    'Scale-up SaaS Enterprise',
    'https://wruhxkwvombesziefvmn.supabase.co/storage/v1/object/public/portfolio/avatars/rian-pratama.jpg',
    'Nadya memiliki kombinasi langka antara pemikiran strategis product management dan ketajaman visual UI/UX kelas atas. Kecepatannya dalam menyederhanakan workflow yang rumit menjadi interface yang intuitif benar-benar mendongkrak retensi produk kami.',
    'Verified Colleague'
  ),
  (
    'Devi Anggraini',
    'Lead Frontend Engineer',
    'Digital Fintech Studio',
    'https://wruhxkwvombesziefvmn.supabase.co/storage/v1/object/public/portfolio/avatars/devi-anggraini.jpg',
    'Bekerja dengan Nadya sangat menyenangkan untuk tim engineering. Dokumentasi PRD-nya sangat rinci, design system di Figma terstruktur rapi dengan token standar, sehingga proses handoff dan slicing berjalan 2x lebih cepat tanpa multitafsir.',
    'Engineering Partner'
  ),
  (
    'Arif Wicaksono',
    'Startup Founder & CEO',
    'TaskFlow Workspace',
    'https://wruhxkwvombesziefvmn.supabase.co/storage/v1/object/public/portfolio/avatars/arif-wicaksono.jpg',
    'Nadya memimpin produk kami dari tahap 0 ke 1 dengan kepemimpinan yang solid. Riset penggunanya tajam, validasi MVP tepat sasaran, dan hasil desainnya mendapat rating kepuasan 4.6/5 saat debut peluncuran.',
    'Founder Endorsement'
  )
ON CONFLICT DO NOTHING;

-- Seed Projects (With Supabase Storage Mockup Images)
INSERT INTO public.projects (id, title, category, description, tags, image, live_url, featured, detail)
VALUES
  (
    'zenith-analytics-redesign',
    'Zenith Analytics — SaaS Dashboard Redesign',
    'Product Design',
    'Merancang ulang dashboard analitik SaaS dengan pendekatan user-centered design, meningkatkan task completion rate sebesar 40%.',
    '["Product Strategy", "Figma", "User Research", "Design System"]'::jsonb,
    'https://wruhxkwvombesziefvmn.supabase.co/storage/v1/object/public/portfolio/projects/zenith-analytics.jpg',
    'https://example.com/zenith',
    true,
    '{"duration": "3 bulan (Sep — Nov 2024)", "role": "Product Manager & Lead UI/UX Designer", "results": [{"metric": "Task Completion Rate", "before": "58%", "after": "81%", "change": "+40%"}, {"metric": "Support Tickets", "before": "35/mgg", "after": "9/mgg", "change": "-74%"}]}'::jsonb
  ),
  (
    'luxe-ecommerce-experience',
    'Luxe Store — E-Commerce UX Overhaul',
    'UX Design',
    'Mendesain ulang pengalaman belanja online end-to-end, dari product discovery hingga checkout, menghasilkan peningkatan konversi 28%.',
    '["UX Research", "Usability Testing", "Figma", "Interaction Design"]'::jsonb,
    'https://wruhxkwvombesziefvmn.supabase.co/storage/v1/object/public/portfolio/projects/luxe-ecommerce.jpg',
    'https://example.com/luxe',
    true,
    '{"duration": "2.5 bulan (Mar — Mei 2024)", "role": "Lead UX Designer", "results": [{"metric": "Conversion Rate", "before": "2.1%", "after": "2.7%", "change": "+28%"}]}'::jsonb
  ),
  (
    'taskflow-management-app',
    'TaskFlow — Project Management App',
    'Product Management',
    'Memimpin pengembangan produk aplikasi manajemen proyek dari 0 ke 1, mengelola roadmap, backlog, dan koordinasi tim cross-functional.',
    '["Product Roadmap", "PRD", "Agile/Scrum", "Figma"]'::jsonb,
    'https://wruhxkwvombesziefvmn.supabase.co/storage/v1/object/public/portfolio/projects/taskflow.jpg',
    'https://example.com/taskflow',
    true,
    '{"duration": "6 bulan (Jan — Jun 2024)", "role": "Lead Product Manager", "results": [{"metric": "Users (3 bln post-launch)", "before": "0", "after": "1,200+", "change": "Dari nol"}, {"metric": "CSAT Score", "before": "-", "after": "4.6/5.0", "change": "Target 4.0"}]}'::jsonb
  ),
  (
    'nexus-design-system',
    'Nexus — Enterprise Design System',
    'Design System',
    'Membangun sistem desain multi-brand komprehensif dengan 120+ komponen, design tokens terstandarisasi, dan dokumentasi Figma yang scalable.',
    '["Design Tokens", "Component Library", "Figma Variables", "WCAG 2.1"]'::jsonb,
    'https://wruhxkwvombesziefvmn.supabase.co/storage/v1/object/public/portfolio/projects/nexus-design-system.jpg',
    'https://example.com/nexus',
    true,
    '{"duration": "4 bulan (Aug — Nov 2023)", "role": "Design System Lead", "results": [{"metric": "Design-to-Dev Velocity", "before": "-", "after": "+50%", "change": "2x lebih cepat"}]}'::jsonb
  )
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  category = EXCLUDED.category,
  description = EXCLUDED.description,
  image = EXCLUDED.image;
